MyStoreProjectWithDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('Store.urls'), namespace='user'))
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.urls import path
from Store import views
app_name = 'Store'
urlpatterns = [
    path('product/list/', views.product_list, name='product_list'),
    path('product/details/<int:product_id>/', views.product_details, name='product_details'),
    path('orderapp/list/', views.orderapp_list, name='orderapp_list'),
    path('orderapp/details/<int:orderapp_id>/', views.orderapp_details, name='orderapp_details'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
]

Store/models.py
from django.db import models
#########################################
from django.contrib.auth.models import User


# TODO:New Field #
class Customer(models.Model):
    class Meta:
        verbose_name = 'مشتری '
        verbose_name_plural = 'مشتری'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='حساب کاربری')
    # important fields that are stored in User model:
    #   first_name, last_name, email, date_joined


    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = ((MALE, 'مرد'), (FEMALE, 'زن'))
    gender = models.IntegerField('جنسیت', choices=GENDER_CHOICES, blank=True)

    address = models.TextField('آدرس',blank=True)
    mobile = models.CharField('تلفن همراه', max_length=11)
    birth_date = models.DateField('تاریخ تولد', null=True, blank=True)
    profile_image = models.ImageField('تصویر', upload_to='profile_images/', null=True, blank=True)
    balance = models.IntegerField('اعتبار', default=0)


    def __str__(self):
        return self.user.get_full_name()

    def get_balance_display(self):
        return '{:,} تومان'.format(self.balance)

    # behaviors
    def deposit(self, amount):
        self.balance += amount
        self.save()

    def spend(self, amount):
        if self.balance < amount:
            return False
        self.balance -= amount
        self.save()
        return True



class Product(models.Model):
    class Meta:
        verbose_name = 'کالا'
        verbose_name_plural = 'کالا'
    ProductName = models.CharField('نام کالا',max_length=50)
    ProductPrice=models.IntegerField('قیمت')

    ProductImage = models.ImageField('تصویر', upload_to='product_images/')
    # TODO:New Field #
    ProductStock = models.IntegerField('موجودی کالا')
    ProductDescription = models.TextField('توضیح مخنصری در مورد کالا')


    Available=1
    NotAvailable=0
    status_choices=(
        (Available,'موجود در انبار'),
        (NotAvailable,'موجودی تا چند روز آینده'),
    )
    ProductStatus=models.IntegerField('وضعیت',choices=status_choices)
    def get_price_display(self):
        return '{:,} تومان'.format(self.ProductPrice)

    def __str__(self):
        return F"{self.ProductName} - {self.ProductPrice}"


    def reserve_stock(self, sell_count):
        assert isinstance(sell_count, int) and sell_count > 0, 'Number of sells should be a positive integer'
        assert self.ProductStatus == Product.Available, 'Product is not Available'
        assert self.ProductStock >= sell_count, 'Not enough ProductStock'
        self.ProductStock -= sell_count
        if self.ProductStock == 0:
            self.ProductStatus = Product.NotAvailable
        self.save()



class OrderApp(models.Model):
    class Meta:
        verbose_name = 'سفارشات '
        verbose_name_plural = 'سفارشات'
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='کالا')
    customer = models.ForeignKey('Customer', on_delete=models.PROTECT, verbose_name='خریدار')
    sell_count = models.IntegerField('تعداد خرید')
    order_time = models.DateTimeField('تاریخ ثبت سفارش', auto_now_add=True)



    def __str__(self):
        return "{} سفارش به نام {} برای کالای {}".format(self.sell_count, self.customer, self.product)


#######################################################################################################################
class Payment(models.Model):
    class Meta:
        verbose_name = 'پرداخت'
        verbose_name_plural = 'پرداخت'

    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, verbose_name='کاربر')
    amount = models.PositiveIntegerField('مبلغ')
    transaction_time = models.DateTimeField('زمان تراکنش', auto_now_add=True)
    transaction_code = models.CharField('رسید تراکنش', max_length=30)
    def get_amount_display(self):
        return '{:,} تومان'.format(self.amount)



    def __str__(self):
        return '{:20,} تومان افزایش اعتبار برای {}'.format(self.amount, self.customer)

Store/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError

from Store.models import *


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount', 'transaction_code']
        # or: exclude = ['profile', 'transaction_time']

    def clean_transaction_code(self):
        code = self.cleaned_data.get('transaction_code')
        try:
            # should be in format: bank-<amount>-<TOKEN>#
            # e.g. bank-30000-UHB454GRH73BDYU#
            assert code.startswith('bank-')
            assert code.endswith('#')
            int(code.split('-')[1])
        except:
            raise ValidationError('قالب رسید تراکنش معتبر نیست')
        return code

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount % 1000 != 0:
            raise ValidationError('مبلغ پرداختی باید ضریبی از هزار تومان باشد')
        return amount

    def clean(self):
        super().clean()
        code = self.cleaned_data.get('transaction_code')
        amount = self.cleaned_data.get('amount')
        if code and amount:
            if int(code.split('-')[1]) != amount:
                raise ValidationError('رسید و مبلغ تراکنش هم‌خوانی ندارند')


class MyUserForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']
    password = None


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['mobile', 'gender', 'address', 'profile_image']

Store/views.py
from datetime import datetime

from django.template.loader import render_to_string

from .forms import *
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# Create your views here.

def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
        'date_now':datetime.now()
    }
    return render(request, 'store/product_list.html', context)

def product_details(request, product_id):
    product = Product.objects.get(pk=product_id)

    context = {
        'product': product,
        'date_now': datetime.now()
    }


    if request.method == 'POST':
        try:
            sell_count = int(request.POST['sell_count'])
            assert product.ProductStatus == product.Available, 'موجودی کالا در انبار به اتمام رسیده است'
            assert product.ProductStock >= sell_count , 'با توجه به موجودی این کالا در انبار در حال حاضر متاسفانه نمی توانیم به این تعداد سفارش پاسخگو باشیم.'
            price = product.ProductPrice * sell_count
            assert request.user.customer.spend(price), 'اعتبار شما برای ثبت سفارش کافی نیست.'
            product.reserve_stock(sell_count)
            order = OrderApp.objects.create(product=product, customer=request.user.customer, sell_count=sell_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('Store:orderapp_details', kwargs={'orderapp_id': order.id}))
    return render(request, 'store/product_details.html', context)



def orderapp_list(request):
    orderapps = OrderApp.objects.filter(customer_id=request.user.customer).order_by('-order_time')
    context = {
        'orderapps': orderapps,
        'date_now': datetime.now()

    }
    return render(request, 'store/orderapp_list.html', context)

def orderapp_details(request, orderapp_id):
    orderapp = OrderApp.objects.get(pk=orderapp_id)
    context = {
        'orderapp': orderapp,
        'date_now': datetime.now()
    }
    return render(request, 'store/orderapp_details.html', context)


#TODO: user and accounts func


def login_view(request):
    next_url = request.GET.get('next')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # Successful login
            login(request, user)
            redirect_url = next_url if next_url else reverse('Store:product_list')
            return HttpResponseRedirect(redirect_url)
        else:
            # undefined user or wrong password
            context = {
                'username': username,
                'date_now': datetime.now(),
                'error': 'کاربری با این مشخصات یافت نشد'

            }
    else:
        context = {'date_now': datetime.now()}
    return render(request, 'user/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Store:login'))



@login_required
def profile_details(request):
    customer = request.user.customer
    context = {
        'customer': customer,
        'date_now': datetime.now()
    }
    return render(request, 'user/profile_details.html', context)


@login_required
def payment_list(request):
    payments = Payment.objects.filter(customer=request.user.customer).order_by('-transaction_time')
    context = {
        'payments': payments,
        'date_now': datetime.now()
    }
    return render(request, 'user/payment_list.html', context)


@login_required
def payment_create(request):
    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment = payment_form.save(commit=False)
            payment.profile = request.user.customer
            payment.save()
            request.user.customer.deposit(payment.amount)
            return HttpResponseRedirect(reverse('Store:payment_list'))
    else:
        payment_form = PaymentForm()
    context = {
        'payment_form': payment_form,
        'date_now': datetime.now()
    }
    return render(request, 'user/payment_create.html', context)


@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = MyUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.customer)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('Store:profile_details'))
    else:
        user_form = MyUserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.customer)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'date_now': datetime.now()
    }
    return render(request, 'user/profile_edit.html', context)

Store/templates/store/_base_page.html
{% load static %}
{% load jalali_tags %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extra_headers %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static "store/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "store/css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "store/css/main.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "user/css/user.css" %}">
    {% block extra_css %}{% endblock %}
</head>
<body dir="rtl">

<div class="container-fluid col-md-12 col-lg-12 col-sm-12">

    <div class="container-fluid ">
        <div class="row align-items-center  " id="header">
<div class="col-12 text-left">
    <div>
        <i class="far fa-calendar-alt"></i>

        <small>
            امروز :
            {{ date_now|to_jalali:'%A %m/%d ساعت %H:%M' }}
        </small>
    </div>
</div>
            <div class="col-12 text-center align-text-top">

                <h2>
                    فروشگاه اینترنتی
                </h2>
            </div>

        </div>
        <div class="row align-items-center " id="toolbar">
            <div class="col-6 container-fluid ">
                <h4>
                    {% block toolbar_title %}{% endblock %}
                </h4>
            </div>
            <div class="col-6 text-left ">
                {% block toolbar_buttons %}
                    <a class="btn btn-light py-1 px-2" href="{% url "Store:product_list" %}">
                        <i class="fas fa-shopping-cart"></i>
                        کالا ها
                    </a>
                {% endblock %}


                {% block user_button %}
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle py-1 px-2" id="user-button" href="#"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i>
                                {{ user.get_full_name }}
                            </a>
                            <div class="dropdown-menu text-right" aria-labelledby="user-button" dir="rtl">
                                <i class="fas fa-wallet"></i>
                                <small>
                                    اعتبار:
                                    {{ user.customer.get_balance_display }}

                                </small>
                                </span>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url "Store:profile_details" %}">
                                    <i class="fas fa-user-tie"></i>
                                    ناحیه کاربری
                                </a>
                                <a class="dropdown-item" href="{% url "Store:orderapp_list" %}">
                                    <i class="fas fa-truck"></i>
                                    سفارشات من
                                </a>
                                <a class="dropdown-item" href="{% url "Store:payment_list" %}">
                                    <i class="fas fa-receipt"></i>
                                    پرداخت‌های من
                                </a>
                                <a class="dropdown-item" href="{% url "Store:logout" %}">
                                    <i class="fas fa-sign-out-alt"></i>
                                    خروج
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <a class="btn btn-primary py-1 px-2 mr-3" href="{% url "Store:login" %}">
                            <i class="fas fa-sign-in-alt"></i>
                            ورود
                        </a>
                    {% endif %}
                {% endblock %}
            </div>

        </div>
        {% block main_content %}{% endblock %}
        <div class="row  align-items-center " id="footer">
            <div class="col text-center container-fluid">
            <span>
                ما را در شبکه‌های اجتماعی دنبال کنید.

                <a class="social-media-icon" href="https://facebook.com/#">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="social-media-icon" href="https://twitter.com/#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="social-media-icon" href="https://instagram.com/#">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="social-media-icon" href="https://telegram.org/#">
                    <i class="fab fa-telegram-plane"></i>
                </a>
            </span>
            </div>
        </div>
    </div>
</div>


<script src="{% static "store/js/jquery-3.4.0.min.js" %}"></script>
<script src="{% static "store/js/bootstrap.bundle.js" %}"></script>
<script src="{% static "store/js/font-awesome.js" %}"></script>
<script src="{% static "store/js/main.js" %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

Store/templates/store/orderapp_details.html
{% extends "store/_base_page.html" %}
{% load static %}
{% load jalali_tags %}

{% block title %}
    مشاهده سفارش
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-shipping-fast"></i>
    مشاهده سفارش
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "Store:product_list" %}">
        <i class="fas fa-list"></i>
        فهرست کالا ها
    </a>
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-clock"></i>
                        زمان خرید:
                    </small>
                </div>
                <div class="col-9">
                    {{ orderapp.order_time|to_jalali:'%A %y/%m/%d ساعت %H:%M' }}
                </div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-calculator"></i>
                        تعداد خرید:
                    </small>
                </div>
                <div class="col-2">
                    {{ orderapp.sell_count }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-user-tie"></i>
                        خریدار:
                    </small>
                </div>
                <div class="col-9">
                    {{ orderapp.customer }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-shopping-cart"></i>
                        نام کالا:
                    </small>
                </div>
                <div class="col-9">
                    {{ orderapp.product.ProductName }}
                </div>

                <div class="w-100 my-1"></div>
                <div class="col-12">
                    <small class="text-muted">
                        <p><i class="fas fa-handshake"></i>
                            ممنون که فروشگاه ما را برای خرید انتخاب کردید .
                        </p>
                        <p>
                            <i class="fas fa-award"></i>
                            از اعتماد شما متشکریم</p>
                    </small>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <img class="img-thumbnail" src="{{ orderapp.product.ProductImage.url }}"
                 alt="{{ orderapp.product.ProductName }}">
        </div>
    </div>
{% endblock %}

Store/templates/store/orderapp_list.html
{% extends "store/_base_page.html" %}
{% load static %}
{% load jalali_tags %}
{% block title %}
    سفارشات من
{% endblock %}

{% block toolbar_title %}
    سفارشات من
{% endblock %}


{% block main_content %}
    <div class="row">
        <div class="col py-4 px-4">
            {% if orderapps %}

                <div class="alert alert-info">
                    در حال حاضر
                    {{ orderapps.count }}
                    سفارش
                    به نام خانم/آقا

                    {{ user.get_full_name }}
                    ثبت شده است .
                </div>
                <div class="row px-3">
                    {% for orderapp in orderapps %}
                        <div class="col-3 px-2 py-2">
                            <a href="{% url "Store:orderapp_details" orderapp_id=orderapp.pk %}"
                               class="showtime-box btn
                                btn-outline-dark">
                                <span>
                                    <img class="img-thumbnail"
                                         src="{{ orderapp.product.ProductImage.url }}"
                                         style="width: 50px; height: 50px;"/></span>
                                <br/>
                                <span>{{ orderapp.product.ProductName }}</span>
                                <br/>
                                <span>{{ orderapp.product.get_price_display }}
                                    </span>

                                <br/>
                                <span>{{ orderapp.sell_count }}                                     <b><i>قلم
                                    </i></b></span>
                                <br/>
                                <span class="showtime-status badge badge-success">
                                        {{ orderapp.order_time|to_jalali:'%A %m/%d ساعت %H:%M' }}
                                </span>
                                <div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="alert alert-danger">
                    در حال حاضر هیچ سفارشی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

Store/templates/store/product_details.html
{% extends "store/_base_page.html" %}
{% load static %}

{% block title %}{{ product.ProductName }}{% endblock %}

{% block toolbar_title %}
<i class="fas fa-shopping-cart"></i>
    {{ product.ProductName }}
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "Store:product_list" %}">
        <i class="fas fa-list"></i>
        فهرست کالا ها
    </a>
{% endblock %}

{% block main_content %}
    <div class="row py-4">
        <div class="col-8 item-details">
            <div class="row px-4">
                <div class="col-3">
                    <small class="text-muted">
                        نام محصول :
                    </small>
                </div>
                <div class="col-9">
                    {{ product.ProductName }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        قیمت محصول :
                    </small>
                </div>
                <div class="col-9">
                    {{ product.get_price_display }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        موجودی در انبار :
                    </small>
                </div>
                <div class="col-9">
                    {{ product.ProductStock }}
                    تعداد
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        شرح محصول:
                    </small>
                </div>
                <div class="col-9 item-text-box">
                    {{ product.ProductDescription }}
                </div>
                {% if product.ProductStatus == product.Available %}
                <div class="col-5">
                    <form action="" method="post" class="form-inline">
                        {% csrf_token %}
                        <select name="sell_count" class="form-control form-control-sm ml-2">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <button type="submit" class="btn btn-xs btn-success my-1" href="#">
                            خرید کالا
                        </button>
                    </form>
                    </div>
                {% endif %}
                            {% if error %}
                    <div class="w-100 my-1"></div>
                    <span class="col-12 alert alert-danger align-items-baseline small p-2">
                        <i class="fas fa-exclamation-circle"></i>
                        {{ error }}
                    </span>
                {% endif %}
            </div>
        </div>
        <div class="container col-4 text-center  ">
            <div class="container-fluid btn-outline-secondary img-thumbnail  "
              >
            <img class="img-thumbnail col-6
              col-6 text-center " src="{{ product.ProductImage.url }}"
                 alt="{{ product.ProductName }}" style="padding: 0px;margin: 0px;">
            <div class="col-6 text-center badge
             {% if product.ProductStatus == product.Available %}
             badge-success
             {% else %}
             badge-warning
            {% endif %}" style="margin: 0px;">
            {% if product.ProductStatus == product.Available %}
                {{ product.get_price_display }}
            {% else %}
                {{ product.get_ProductStatus_display }}
            {% endif %}
            </div>
        </div>
        </div>

    </div>

{% endblock %}

Store/templates/store/product_list.html
{% extends "store/_base_page.html" %}
{% load static %}

{% block title %}
    فهرست کالا‌ها
{% endblock %}

{% block toolbar_title %}
    فهرست کالا‌ها
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col py-4 px-4">
            {% if products %}
                <div class="row px-3">
                    {% for product in products %}
                        <div class="col-3 px-2 py-2">
                            <a href="{% url "Store:product_details" product_id=product.pk %}"
                               class="product-box btn
                                {% if product.ProductStatus != product.Available %}
                                  btn-secondary
                                {% else %}
                                 btn-outline-dark
                                {% endif %}">
                                <span>
                                    <img class="img-thumbnail"
                                         src="{{ product.ProductImage.url }}"
                                         style="width: 50px; height: 50px;"/></span>
                                <br/>
                                <span>{{ product.ProductName }}</span>
                                <br/>

                                <span class="product-status badge
                                    {% if product.ProductStatus == product.Available %}
                                        badge-success
                                    {% else %}
                                        badge-warning
                                    {% endif %}">
                                    {% if product.ProductStatus == product.Available %}
                                        {{ product.get_price_display }}
                                    {% else %}
                                        {{ product.get_ProductStatus_display }}
                                    {% endif %}
                                </span>
                            <div>
                                {% if product.ProductStatus == product.Available and product.ProductStock > 5 %}

                                    <span class="badge badge-danger">
                                                                    {{ product.ProductStock }}
                                                                    موجودی کالا
                                                                    </span>
                                {% endif %}
                            </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="alert alert-danger">
                    در حال حاضر هیچ کالایی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}