MyStoreProjectWithDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('Store.urls'), namespace='user'))
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.urls import path
from Store import views
app_name = 'Store'
urlpatterns = [
    path('product/list/', views.product_list, name='product_list'),
    path('product/details/<int:product_id>/', views.product_details, name='product_details'),
    path('orderapp/list/', views.orderapp_list, name='orderapp_list'),
    path('orderapp/details/<int:orderapp_id>/', views.orderapp_details, name='orderapp_details'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
]

Store/models.py
from django.db import models
#########################################
from django.contrib.auth.models import User


# TODO:New Field #
class Customer(models.Model):
    class Meta:
        verbose_name = 'مشتری '
        verbose_name_plural = 'مشتری'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='حساب کاربری')
    # important fields that are stored in User model:
    #   first_name, last_name, email, date_joined


    MALE = 1
    FEMALE = 2
    GENDER_CHOICES = ((MALE, 'مرد'), (FEMALE, 'زن'))
    gender = models.IntegerField('جنسیت', choices=GENDER_CHOICES, blank=True)

    address = models.TextField('آدرس',blank=True)
    mobile = models.CharField('تلفن همراه', max_length=11)
    birth_date = models.DateField('تاریخ تولد', null=True, blank=True)
    profile_image = models.ImageField('تصویر', upload_to='profile_images/', null=True, blank=True)
    balance = models.IntegerField('اعتبار', default=0)


    def __str__(self):
        return self.user.get_full_name()

    def get_balance_display(self):
        return '{:,} تومان'.format(self.balance)

    # behaviors
    def deposit(self, amount):
        self.balance += amount
        self.save()

    def spend(self, amount):
        if self.balance < amount:
            return False
        self.balance -= amount
        self.save()
        return True



class Product(models.Model):
    class Meta:
        verbose_name = 'کالا'
        verbose_name_plural = 'کالا'
    ProductName = models.CharField('نام کالا',max_length=50)
    ProductPrice=models.IntegerField('قیمت')

    ProductImage = models.ImageField('تصویر', upload_to='product_images/')
    # TODO:New Field #
    ProductStock = models.IntegerField('موجودی کالا')
    ProductDescription = models.TextField('توضیح مخنصری در مورد کالا')


    Available=1
    NotAvailable=0
    status_choices=(
        (Available,'موجود در انبار'),
        (NotAvailable,'موجودی تا چند روز آینده'),
    )
    ProductStatus=models.IntegerField('وضعیت',choices=status_choices)
    def get_price_display(self):
        return '{:,} تومان'.format(self.ProductPrice)

    def __str__(self):
        return F"{self.ProductName} - {self.ProductPrice}"


    def reserve_stock(self, sell_count):
        assert isinstance(sell_count, int) and sell_count > 0, 'Number of sells should be a positive integer'
        assert self.ProductStatus == Product.Available, 'Product is not Available'
        assert self.ProductStock >= sell_count, 'Not enough ProductStock'
        self.ProductStock -= sell_count
        if self.ProductStock == 0:
            self.ProductStatus = Product.NotAvailable
        self.save()



class OrderApp(models.Model):
    class Meta:
        verbose_name = 'سفارشات '
        verbose_name_plural = 'سفارشات'
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='کالا')
    customer = models.ForeignKey('Customer', on_delete=models.PROTECT, verbose_name='خریدار')
    sell_count = models.IntegerField('تعداد خرید')
    order_time = models.DateTimeField('تاریخ ثبت سفارش', auto_now_add=True)



    def __str__(self):
        return "{} سفارش به نام {} برای کالای {}".format(self.sell_count, self.customer, self.product)


#######################################################################################################################
class Payment(models.Model):
    class Meta:
        verbose_name = 'پرداخت'
        verbose_name_plural = 'پرداخت'

    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, verbose_name='کاربر')
    amount = models.PositiveIntegerField('مبلغ')
    transaction_time = models.DateTimeField('زمان تراکنش', auto_now_add=True)
    transaction_code = models.CharField('رسید تراکنش', max_length=30)
    def get_amount_display(self):
        return '{:,} تومان'.format(self.amount)



    def __str__(self):
        return '{:20,} تومان افزایش اعتبار برای {}'.format(self.amount, self.customer)

Store/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError

from Store.models import *


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount', 'transaction_code']
        # or: exclude = ['profile', 'transaction_time']

    def clean_transaction_code(self):
        code = self.cleaned_data.get('transaction_code')
        try:
            # should be in format: bank-<amount>-<TOKEN>#
            # e.g. bank-30000-UHB454GRH73BDYU#
            assert code.startswith('bank-')
            assert code.endswith('#')
            int(code.split('-')[1])
        except:
            raise ValidationError('قالب رسید تراکنش معتبر نیست')
        return code

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if amount % 1000 != 0:
            raise ValidationError('مبلغ پرداختی باید ضریبی از هزار تومان باشد')
        return amount

    def clean(self):
        super().clean()
        code = self.cleaned_data.get('transaction_code')
        amount = self.cleaned_data.get('amount')
        if code and amount:
            if int(code.split('-')[1]) != amount:
                raise ValidationError('رسید و مبلغ تراکنش هم‌خوانی ندارند')


class MyUserForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']
    password = None


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['mobile', 'gender', 'address', 'profile_image']

Store/views.py
from datetime import datetime

from django.template.loader import render_to_string

from .forms import *
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# Create your views here.

def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
        'date_now':datetime.now()
    }
    return render(request, 'store/product_list.html', context)

def product_details(request, product_id):
    product = Product.objects.get(pk=product_id)

    context = {
        'product': product,
        'date_now': datetime.now()
    }


    if request.method == 'POST':
        try:
            sell_count = int(request.POST['sell_count'])
            assert product.ProductStatus == product.Available, 'موجودی کالا در انبار به اتمام رسیده است'
            assert product.ProductStock >= sell_count , 'با توجه به موجودی این کالا در انبار در حال حاضر متاسفانه نمی توانیم به این تعداد سفارش پاسخگو باشیم.'
            price = product.ProductPrice * sell_count
            assert request.user.customer.spend(price), 'اعتبار شما برای ثبت سفارش کافی نیست.'
            product.reserve_stock(sell_count)
            order = OrderApp.objects.create(product=product, customer=request.user.customer, sell_count=sell_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('Store:orderapp_details', kwargs={'orderapp_id': order.id}))
    return render(request, 'store/product_details.html', context)



def orderapp_list(request):
    orderapps = OrderApp.objects.filter(customer_id=request.user.customer).order_by('-order_time')
    context = {
        'orderapps': orderapps,
        'date_now': datetime.now()

    }
    return render(request, 'store/orderapp_list.html', context)

def orderapp_details(request, orderapp_id):
    orderapp = OrderApp.objects.get(pk=orderapp_id)
    context = {
        'orderapp': orderapp,
        'date_now': datetime.now()
    }
    return render(request, 'store/orderapp_details.html', context)


#TODO: user and accounts func


def login_view(request):
    next_url = request.GET.get('next')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # Successful login
            login(request, user)
            redirect_url = next_url if next_url else reverse('Store:product_list')
            return HttpResponseRedirect(redirect_url)
        else:
            # undefined user or wrong password
            context = {
                'username': username,
                'date_now': datetime.now(),
                'error': 'کاربری با این مشخصات یافت نشد'

            }
    else:
        context = {'date_now': datetime.now()}
    return render(request, 'user/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Store:login'))



@login_required
def profile_details(request):
    customer = request.user.customer
    context = {
        'customer': customer,
        'date_now': datetime.now()
    }
    return render(request, 'user/profile_details.html', context)


@login_required
def payment_list(request):
    payments = Payment.objects.filter(customer=request.user.customer).order_by('-transaction_time')
    context = {
        'payments': payments,
        'date_now': datetime.now()
    }
    return render(request, 'user/payment_list.html', context)


@login_required
def payment_create(request):
    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment = payment_form.save(commit=False)
            payment.profile = request.user.customer
            payment.save()
            request.user.customer.deposit(payment.amount)
            return HttpResponseRedirect(reverse('Store:payment_list'))
    else:
        payment_form = PaymentForm()
    context = {
        'payment_form': payment_form,
        'date_now': datetime.now()
    }
    return render(request, 'user/payment_create.html', context)


@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = MyUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.customer)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('Store:profile_details'))
    else:
        user_form = MyUserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.customer)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'date_now': datetime.now()
    }
    return render(request, 'user/profile_edit.html', context)

Store/templates/user/_base_users.html
{% extends "store/_base_page.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "user/css/user.css" %}">
{% endblock %}

Store/templates/user/login.html
{% extends "user/_base_users.html" %}
{% load static %}

{% block title %}ورود کاربران{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
    ورود کاربران
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="login-form">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endif %}
        <div class="form-group row">
            <label class="col-3">نام کاربری:</label>
            <input class="col-9 form-control" type="text" name="username" value="{{ username }}" />
        </div>
        <div class="form-group row">
            <label class="col-3">گذرواژه:</label>
            <input class="col-9 form-control" type="password" name="password" />
        </div>
        <div class="form-group row justify-content-center">
            <div class="col-4">
                <button type="submit" class="btn btn-success w-100">
                    ورود
                </button>
            </div>
        </div>
    </form>
{% endblock %}

Store/templates/user/payment_create.html
{% extends "user/_base_users.html" %}
{% load static %}

{% block title %}
    پرداخت جدید
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-plus"></i>
    پرداخت جدید
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="form py-2">
        {% csrf_token %}
        <table class="my-1">
        {{ payment_form.as_table }}
        </table>
        <button type="submit" class="btn btn-success btn-sm">
            ثبت
        </button>
    </form>
{% endblock %}

Store/templates/user/payment_list.html
{% extends "user/_base_users.html" %}
{% load static %}
{% load jalali_tags %}
{% block title %}
    پرداخت‌های من
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-receipt"></i>
    پرداخت‌های من
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-12 mt-2">
            <a href="{% url "user:payment_create" %}" class="btn btn-success btn-sm">
                <i class="fas fa-plus"></i>
                پرداخت جدید
            </a>
        </div>
        <div class="col py-3">
            {% if payments %}
                <ul class="item-list">
                    {% for payment in payments %}
                        <li>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    مبلغ:
                                </span>
                                {{ payment.get_amount_display }}
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    تاریخ تراکنش:
                                </span>
                                {{ payment.transaction_time|to_jalali:'%A %y/%m/%d ساعت %H:%M'}}
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">
                                    رسید تراکنش:
                                </span>
                                {{ payment.transaction_code }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger">
                    هیچ تراکنشی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

Store/templates/user/profile_details.html
{% extends "user/_base_users.html" %}
{% load static %}
{% load jalali_tags %}

{% block title %}{{ customer }}{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
    مشاهده نمایه
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-user"></i>
                        نام کاربری:
                    </small>
                </div>
                <div class="col-8">
                    {{ customer.user.username }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-address-card"></i>
                        نام و نام خانوادگی:
                    </small>
                </div>
                <div class="col-8">
                    {{ customer.user.get_full_name }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-birthday-cake"></i>
                        تاریخ تولد:
                    </small>
                </div>
                <div class="col-8">
                    {{ customer.birth_date|to_jalali:'%A %y/%m/%d '  }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-mobile-alt"></i>
                        تلفن همراه:
                    </small>
                </div>
                <div class="col-8">
                    {{ customer.mobile }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-coins"></i>
                        اعتبار:
                    </small>
                </div>
                <div class="col-4">
                    {{ customer.get_balance_display }}
                </div>
                <div class="col-4 text-left">
                    <a class="btn btn-xs btn-success my-1" href="{% url "user:payment_create" %}">
                        <i class="fas fa-plus"></i>
                        افزایش اعتبار
                    </a>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <i class="fas fa-home"></i>
                        آدرس:
                    </small>
                </div>
                <div class="col-10 item-text-box">
                    {{ customer.address }}
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
        {% if customer.profile_image %}
                <img class="profile-image" src="{{ customer.profile_image.url }}" alt="{{ customer }}">
        {% endif %}
            <div class="profile-buttons mt-4">
                <a class="btn btn-secondary" href="{% url "user:profile_edit" %}">
                    <i class="fas fa-edit"></i>
                    ویرایش نمایه
                </a>
                <a class="btn btn-warning" href="#">
                    <i class="fas fa-key"></i>
                    تغییر گذرواژه
                </a>
            </div>
        </div>
    </div>
{% endblock %}

Store/templates/user/profile_edit.html
{% extends "user/_base_users.html" %}
{% load static %}

{% block title %}
    ویرایش نمایه
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-edit"></i>
    ویرایش نمایه
{% endblock %}

{% block main_content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row py-3">
            <div class="col-10 item-details profile-items">
                <div class="row px-3">
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-user"></i>
                            نام کاربری:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user.username }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="far fa-clock"></i>
                            جنسیت:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ profile_form.gender }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-address-card"></i>
                            نام:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.first_name }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="far fa-address-card"></i>
                            نام خانوادگی:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.last_name }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="far fa-envelope-open"></i>
                            ایمیل:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ user_form.email }}
                    </div>
                    <div class="col-2 pl-0">
                        <small class="text-muted">
                            <i class="fas fa-mobile-alt"></i>
                            تلفن همراه:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ profile_form.mobile }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <small class="text-muted">
                            <i class="fas fa-home"></i>
                            آدرس:
                        </small>
                    </div>
                    <div class="col-10 item-text-box">
                        {{ profile_form.address }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <button type="submit" class="btn btn-primary btn-sm">
                        ذخیره
                    </button>
                </div>
            </div>
            <div class="col-2 pr-0 text-center">
                {% if user.profile.profile_image %}
                    <img class="profile-image" src="{{ user.profile.profile_image.url }}" alt="{{ user.profile }}">
                {% endif %}
                <button type="button" class="btn btn-warning btn-sm mt-2"
                        data-toggle="modal" data-target="#profile-image-modal">
                    <i class="fas fa-image"></i>
                </button>
                <div class="modal fade" id="profile-image-modal">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-body">
                            {{ profile_form.profile_image }}
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}